// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  bento_grid: dynamic(() => import("./BentoGrid")),
  customer_brand: dynamic(() => import("./CustomerBrand")),
  graphic_bloc: dynamic(() => import("./GraphicBloc")),
  hero_section: dynamic(() => import("./HeroSection")),
  image_block: dynamic(() => import("./ImageBlock")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  rich_text: dynamic(() => import("./RichText")),
  socials: dynamic(() => import("./Socials")),
  trusted_by: dynamic(() => import("./TrustedBy")),
};
